# Generated by Django 2.1.5 on 2019-02-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='is_deleted',
            field=models.DateTimeField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_deleted',
            field=models.DateTimeField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='is_deleted',
            field=models.DateTimeField(default=False, null=True),
        ),
    ]
