# Generated by Django 2.1.5 on 2019-02-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='sub_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
