# Generated by Django 2.1.5 on 2019-02-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0003_plant_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='purchase_history',
            new_name='owner',
        ),
    ]
