# Generated by Django 2.1.5 on 2019-02-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0004_auto_20190209_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
