# Generated by Django 2.1.5 on 2019-02-21 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0004_auto_20190220_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='greenhouse.Group'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='greenhouse.PlantType'),
        ),
    ]
