# Generated by Django 2.1.5 on 2019-02-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0005_auto_20190209_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='death_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
