# Generated by Django 2.1.5 on 2019-02-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0005_auto_20190221_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.Group'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.PlantType'),
        ),
    ]
