# Generated by Django 2.1.5 on 2019-02-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0006_auto_20190223_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
