# Generated by Django 2.1.5 on 2019-02-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0006_auto_20190209_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
