# Generated by Django 2.1.5 on 2019-02-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0007_auto_20190209_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
