# Generated by Django 2.1.5 on 2019-02-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0009_auto_20190209_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
