# Generated by Django 2.1.5 on 2019-02-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0011_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='owner',
        ),
    ]
