# Generated by Django 2.1.5 on 2019-02-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0012_remove_control_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='capture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='humidity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
