# Generated by Django 2.1.5 on 2019-02-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0014_auto_20190211_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='capture_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
