# Generated by Django 2.1.5 on 2019-02-11 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0015_auto_20190211_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='code',
        ),
    ]
