# Generated by Django 2.1.5 on 2019-02-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0016_remove_control_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
